name: oncontrol
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  http: ^0.13.5
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  table_calendar: ^3.0.9
  stomp_dart_client: ^2.1.3
  image_picker: ^1.0.4
  intl: ^0.20.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.0.0
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/onconpat.png"
